# Generated by Django 2.0.7 on 2019-01-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190111_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'News Post'},
        ),
        migrations.AddField(
            model_name='archivedfile',
            name='brief_summary',
            field=models.CharField(default="Here's a brief summary!", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='brief_summary',
            field=models.CharField(default='kirk', max_length=1000),
            preserve_default=False,
        ),
    ]
