# Generated by Django 2.0.7 on 2019-01-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190111_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='vintage',
            field=models.DateField(default='1989-05-17', help_text='When was this file created/intended for/relevant? Ex: 05/17/1989'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedfile',
            name='vintage',
            field=models.DateField(help_text='When was this file created/intended for/relevant? Ex: 05/17/1989'),
        ),
    ]
