# Generated by Django 2.1.5 on 2019-08-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190115_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(help_text='This will sort the new posts, the newest one will be featured'),
        ),
    ]
