# Generated by Django 2.0.7 on 2018-07-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('coffee_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('origin_info', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'Call for more info')], default='yes', max_length=5)),
                ('availability', models.CharField(help_text='Where is this coffee available? (SEA, SF, NJ)', max_length=300)),
            ],
        ),
    ]
