# Generated by Django 2.0.7 on 2018-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20180714_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.CharField(default='Mexico', max_length=200),
            preserve_default=False,
        ),
    ]
