# Generated by Django 2.1.5 on 2019-08-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_auto_20190809_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='bag_tag',
            field=models.CharField(default='GTN3702004', help_text='Put the exact bag tag here, it creates button hyperlinks!', max_length=10),
            preserve_default=False,
        ),
    ]
