# Generated by Django 2.1.5 on 2019-08-21 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_coffee_bag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_current', models.DateField(help_text="This date will show on the web site as the 'current as of' date and the newest file will be linked to on the website.")),
                ('pdf_file', models.FileField(help_text='This will only accept PDF files!', upload_to='offering_lists/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
