# Generated by Django 2.1.5 on 2020-04-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_offeringslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(help_text="Write out exactly how you would like it to show on the banner, be sure to include 'click here'!", max_length=100)),
                ('page_title', models.CharField(help_text='Write out exactly how you would like it to show as a title on the modal page!', max_length=100)),
                ('content', models.TextField()),
                ('is_live', models.BooleanField(help_text='Check this box to show the banner on the website!')),
            ],
        ),
    ]
